#!/bin/bash
set -e

IMAGE=${1:-rancher/cattle-agent-binaries:$(git rev-parse HEAD)}

cd $(dirname $0)/..

./script/wrap build

cd dist
cp ../Dockerfile.image Dockerfile

docker build -t ${IMAGE} .

echo ${IMAGE} > images
